# Generated by Django 3.1.2 on 2020-10-08 05:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Big Band', 'Big Band'), ('Blues Contemporary', 'Blues Contemporary'), ('Seasonal', 'Seasonal'), ('Country Traditional', 'Country Traditional'), ('Dance', 'Dance'), ('Electronica', 'Electronica'), ('Experimental', 'Experimental'), ('Folk International', 'Folk International'), ('Gospel', 'Gospel'), ('Grunge Emo', 'Grunge Emo'), ('Hip Hop Rap', 'Hip Hop Rap'), ('Jazz Classic', 'Jazz Classic'), ('Metal Alternative', 'Metal Alternative'), ('Metal Death', 'Metal Death'), ('Metal Heavy', 'Metal Heavy'), ('Pop Contemporary', 'Pop Contemporary'), ('Pop Indie', 'Pop Indie'), ('Pop Latin', 'Pop Latin'), ('Punk', 'Punk'), ('Reggae', 'Reggae'), ('Rock Alternative', 'Rock Alternative'), ('Rock College', 'Rock College'), ('Rock Contemporary', 'Rock Contemporary'), ('Rock Hard', 'Rock Hard'), ('Rock Neo Psychedelia', 'Rock Neo Psychedelia')], max_length=40, null=True), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre_preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Big Band', 'Big Band'), ('Blues Contemporary', 'Blues Contemporary'), ('Seasonal', 'Seasonal'), ('Country Traditional', 'Country Traditional'), ('Dance', 'Dance'), ('Electronica', 'Electronica'), ('Experimental', 'Experimental'), ('Folk International', 'Folk International'), ('Gospel', 'Gospel'), ('Grunge Emo', 'Grunge Emo'), ('Hip Hop Rap', 'Hip Hop Rap'), ('Jazz Classic', 'Jazz Classic'), ('Metal Alternative', 'Metal Alternative'), ('Metal Death', 'Metal Death'), ('Metal Heavy', 'Metal Heavy'), ('Pop Contemporary', 'Pop Contemporary'), ('Pop Indie', 'Pop Indie'), ('Pop Latin', 'Pop Latin'), ('Punk', 'Punk'), ('Reggae', 'Reggae'), ('Rock Alternative', 'Rock Alternative'), ('Rock College', 'Rock College'), ('Rock Contemporary', 'Rock Contemporary'), ('Rock Hard', 'Rock Hard'), ('Rock Neo Psychedelia', 'Rock Neo Psychedelia')], max_length=40, null=True), blank=True, default=list, size=None),
        ),
    ]
